export type Product = {
  id: number;
  name: string;
  brand: string;
  category: "men" | "women" | "kids";
  subCategory: string;
  price: number;
  old_price?: number;
  stock: number;
  best_seller?: boolean;
  new_arrival?: boolean;
  rating?: number;
  image: string;
  images: string[];
  tags: string[];
  description: string;
  colors: string[];
};

export type GiftOption = {
  id: number;
  name: string;
  category: "boxes" | "packets" | "chocolates" |"candies" | "decoration";
  price: number;
  stock: number;
  image: string;
  tags: string[];
};

export const products: Product[] = [
  {
    id: 1,
    name: "روليكس شامواه",
    brand: "Rolex",
    category: "men",
    subCategory: "ساعات",
    price: 250,
    old_price: 300,
    stock: 4,
    image: "/images/product/id=1.jpg",
    images: ["/images/product/id=1-1.jpg", "/images/product/id=1-2.jpg", "/images/product/id=1-3.jpg", "/images/product/id=1.jpg"],
    tags: ["روليكس", "ساعة", "رجالي", "جلد", "كلاسيكي"],
    description: "ساعة فاخرة بتصميم كلاسيكي.",
    colors: ["Royalblue", "white", "Darkgreen"],
  },
  {
    id: 2,
    name: "كاسيو كلاسيك",
    brand: "Casio",
    category: "men",
    subCategory: "ساعات",
    price: 250,
    old_price: 300,
    stock: 2,
    image: "/images/product/id=2.jpg",
    images: ["/images/product/id=2.jpg", "/images/product/id=2-1.jpg", "/images/product/id=2-2.jpg", "/images/product/id=2-3.jpg"],
    tags: ["كاسيو", "ساعة", "رجالي", "رقمية", "فاخر"],
    description: "أضف لمسة من الرقي إلى معصمك مع هذه الساعة الفاخرة.",
    colors: ["أزرق", "أبيض", "أخضر"],
  },
  {
    id: 3,
    name: "روليكس شامواه",
    brand: "Rolex",
    category: "men",
    subCategory: "ساعات",
    price: 250,
    old_price: 300,
    stock: 4,
    image: "/images/product/id=3.jpg",
    images: ["/images/product/id=3.jpg", "/images/product/id=3-1.jpg", "/images/product/id=3-2.jpg", "/images/product/id=3-3.jpg"],
    tags: ["روليكس", "ساعة", "رجالي", "جلد", "كلاسيكي"],
    description: "ساعة فاخرة بتصميم كلاسيكي.",
    colors: ["أسود", "بني", "بيج"],
  },
  {
    id: 1113,
    name: "روليكس شامواه",
    brand: "Rolex",
    category: "men",
    subCategory: "ساعات",
    price: 250,
    old_price: 300,
    stock: 4,
    image: "/images/product/id=4.jpg",
    images: ["/images/product/watch1-2.jpg", "/images/product/watch1-1.jpg", "/images/product/watch1-2.jpg", "/images/product/watch1-3.jpg"],
    tags: ["روليكس", "ساعة", "رجالي", "جلد", "كلاسيكي"],
    description: "ساعة فاخرة بتصميم كلاسيكي.",
    colors: ["أسود", "بني", "بيج"],
  },
  {
    id: 223,
    name: "روليكس شامواه",
    brand: "Rolex",
    category: "men",
    subCategory: "ساعات رجالية",
    price: 250,
    old_price: 300,
    stock: 4,
    image: "/images/product/watch1.jpg",
    images: ["/images/product/watch1-3.jpg", "/images/product/watch1-1.jpg", "/images/product/watch1-2.jpg", "/images/product/watch1-3.jpg"],
    tags: ["روليكس", "ساعة", "رجالي", "جلد", "كلاسيكي"],
    description: "ساعة فاخرة بتصميم كلاسيكي.",
    colors: ["أسود", "بني", "بيج"],
  },
  {
    id: 553,
    name: "روليكس شامواه",
    brand: "Rolex",
    category: "men",
    subCategory: "ساعات رجالية",
    price: 250,
    old_price: 300,
    stock: 4,
    image: "/images/product/watch1.jpg",
    images: ["/images/product/watch1-1.jpg", "/images/product/watch1-1.jpg", "/images/product/watch1-2.jpg", "/images/product/watch1-3.jpg"],
    tags: ["روليكس", "ساعة", "رجالي", "جلد", "كلاسيكي"],
    description: "ساعة فاخرة بتصميم كلاسيكي.",
    colors: ["أسود", "بني", "بيج"],
  },
  {
    id: 4,
    name: "فوسيل",
    brand: "Fossil",
    category: "men",
    subCategory: "ساعات",
    price: 250,
    old_price: 320,
    stock: 5,
    image: "/images/product/watch3.jpg",
    images: ["/images/product/watch3.jpg", "/images/product/watch3-1.jpg", "/images/product/watch3-2.jpg", "/images/product/watch3-3.jpg"],
    tags: ["فوسيل", "ساعة", "رجالي", "جلد", "كاجوال"],
    description: "وصف روليكس جلد ابيض",
    colors: ["بيج", "أسود"],
  },
  {
    id: 5,
    name: "مونت بلانك",
    brand: "Montblanc",
    category: "men",
    subCategory: "ساعات رجالية",
    price: 230,
    old_price: 300,
    stock: 5,
    image: "/images/product/watch4.jpg",
    images: ["/images/product/watch4.jpg", "/images/product/watch4-1.jpg", "/images/product/watch4-2.jpg", "/images/product/watch4-3.jpg"],
    tags: ["مونت بلانك", "ساعة", "رجالي", "جلد", "رسمي"],
    description: "وصف روليكس جلداخضر",
    colors: ["بني", "أسود"],
  },
  {
    id: 6,
    name: "محفظة جلد جامد رجالي",
    brand: "Natural Leather",
    category: "men",
    subCategory: "محافظ رجالية",
    price: 240,
    old_price: 300,
    stock: 1,
    image: "/images/men/wallet1.jpg",
    images: ["/images/men/wallet1.jpg", "/images/men/wallet2.jpg", "/images/men/wallet3.jpg", "/images/men/wallet4.jpg"],
    tags: ["محفظة", "رجالي", "جلد", "كلاسيكية"],
    description: "وصف محفظة جلد جامد رجالي",
    colors: ["بني", "أسود"],
  },
  {
    id: 7,
    name: "محفظة جلد صناعي",
    brand: "Synthetic Leather",
    category: "men",
    subCategory: "محافظ",
    price: 280,
    old_price: 300,
    stock: 1,
    image: "/images/men/wallet2.jpg",
    images: ["/images/men/wallet2.jpg", "/images/men/wallet2.jpg", "/images/men/wallet3.jpg", "/images/men/wallet4.jpg"],
    tags: ["محفظة", "رجالي", "جلد", "حديثة"],
    description: "وصف محفظة جلد صناعي رجالي",
    colors: ["رمادي", "أزرق"],
  },
  {
    id: 8,
    name: "عطر جلد رجالي",
    brand: "Arabian Oud",
    category: "men",
    subCategory: "عطور",
    price: 251,
    old_price: 300,
    stock: 1,
    image: "/images/men/perfume1.jpg",
    images: ["/images/men/perfume1.jpg", "/images/men/perfume1.jpg", "/images/men/perfume3.jpg", "/images/men/perfume4.jpg"],
    tags: ["عطر", "رجالي", "جلد", "شرقي"],
    description: "وصف عطر جلد رجالي",
    colors: ["بني"],
  },
  {
    id: 9,
    name: "عطر رجالي فاخر",
    brand: "French Perfume",
    category: "men",
    subCategory: "عطور رجالية",
    price: 2830,
    old_price: 300,
    stock: 1,
    image: "/images/men/perfume2.jpg",
    images: ["/images/men/perfume2.jpg", "/images/men/perfume1.jpg", "/images/men/perfume3.jpg", "/images/men/perfume4.jpg"],
    tags: ["عطر", "رجالي", "فاخر", "منعش"],
    description: "وصف عطر رجالي فاخر",
    colors: ["أزرق", "أسود", "رمادي"],
  },
  {
    id: 10,
    name: "بخاخ جسم رجالي",
    brand: "Body Spray",
    category: "men",
    subCategory: "بخاخات رجالية",
    price: 251,
    old_price: 300,
    stock: 1,
    image: "/images/men/spray1.jpg",
    images: ["/images/men/spray1.jpg", "/images/men/spray1.jpg", "/images/men/spray3.jpg", "/images/men/spray4.jpg"],
    tags: ["عطر", "رجالي", "بخاخ", "خشبي"],
    description: "وصف بخاخ جسم رجالي",
    colors: ["بني", "أخضر"],
  },
  {
    id: 11,
    name: "بخاخ جسم منعش",
    brand: "Body Spray",
    category: "men",
    subCategory: "بخاخات رجالية",
    price: 280,
    old_price: 300,
    stock: 1,
    image: "/images/men/spray2.jpg",
    images: ["/images/men/spray2.jpg", "/images/men/spray1.jpg", "/images/men/spray3.jpg", "/images/men/spray4.jpg"],
    tags: ["عطر", "رجالي", "بخاخ", "حمضي"],
    description: "وصف بخاخ جسم منعش",
    colors: ["رمادي", "أحمر"],
  },
  {
    id: 12,
    name: "نظارة شمسية كلاسيكية",
    brand: "Rayban",
    category: "men",
    subCategory: "نظارات شمسية رجالية",
    price: 272,
    old_price: 300,
    stock: 1,
    image: "/images/men/sunglasses1.jpg",
    images: ["/images/men/sunglasses1.jpg", "/images/men/sunglasses2.jpg", "/images/men/sunglasses3.jpg", "/images/men/sunglasses4.jpg"],
    tags: ["نظارة", "رجالي", "شمسية", "كلاسيكية"],
    description: "وصف نظارة شمسية كلاسيكية",
    colors: ["أسود", "فضي"],
  },
  {
    id: 13,
    name: "نظارة شمسية عصرية",
    brand: "Police",
    category: "men",
    subCategory: "نظارات شمسية رجالية",
    price: 280,
    old_price: 300,
    stock: 1,
    image: "/images/men/sunglasses2.jpg",
    images: ["/images/men/sunglasses2.jpg", "/images/men/sunglasses2.jpg", "/images/men/sunglasses3.jpg", "/images/men/sunglasses4.jpg"],
    tags: ["نظارة", "رجالي", "شمسية", "حديثة"],
    description: "وصف نظارة شمسية عصرية",
    colors: ["أزرق", "أحمر", "أسود"],
  },
  {
    id: 14,
    name: "حقيبة يد جلدية",
    brand: "Leather Bags",
    category: "men",
    subCategory: "حقائب يد رجالية",
    price: 272,
    old_price: 300,
    stock: 1,
    image: "/images/men/bag1.jpg",
    images: ["/images/men/bag1.jpg"],
    tags: ["حقيبة", "يد", "رجالي", "جلد"],
    description: "وصف حقيبة يد جلدية",
    colors: ["أسود", "بني"],
  },
  {
    id: 15,
    name: "حقيبة يد قماش",
    brand: "Canvas Bags",
    category: "men",
    subCategory: "حقائب يد رجالية",
    price: 280,
    old_price: 300,
    stock: 1,
    image: "/images/men/bag2.jpg",
    images: ["/images/men/bag2.jpg"],
    tags: ["حقيبة", "يد", "رجالي", "قماش"],
    description: "وصف حقيبة يد قماش",
    colors: ["رمادي", "بيج"],
  },
  {
    id: 16,
    name: "ساعة روليكس جلد احمر",
    brand: "Rolex",
    category: "women",
    subCategory: "ساعات نسائية",
    price: 350,
    old_price: 450,
    stock: 1,
    image: "/images/women/watch1.jpg",
    images: ["/images/women/watch1.jpg"],
    tags: ["روليكس", "ساعة", "نسائي", "جلد", "فاخرة"],
    description: "وصف ساعة روليكس جلد احمر",
    colors: ["أحمر", "وردي", "أبيض"],
  },
  {
    id: 17,
    name: "ساعة أنيقة",
    brand: "Cartier",
    category: "women",
    subCategory: "ساعات نسائية",
    price: 380,
    old_price: 450,
    stock: 1,
    image: "/images/women/watch2.jpg",
    images: ["/images/women/watch2.jpg"],
    tags: ["ساعة", "نسائي", "معدن", "أنيقة"],
    description: "وصف ساعة أنيقة",
    colors: ["ذهبي", "فضي"],
  },
  {
    id: 18,
    name: "عطر زهرة",
    brand: "Floral Perfume",
    category: "women",
    subCategory: "عطور نسائية",
    price: 300,
    old_price: 400,
    stock: 2,
    image: "/images/women/perfume1.jpg",
    images: ["/images/women/perfume1.jpg"],
    tags: ["عطر", "نسائي", "زهري", "رومانسي"],
    description: "وصف عطر زهرة",
    colors: ["أصفر", "وردي"],
  },
  {
    id: 19,
    name: "عطر المساء",
    brand: "Musky Perfume",
    category: "women",
    subCategory: "عطور نسائية",
    price: 450,
    old_price: 550,
    stock: 1,
    image: "/images/women/perfume2.jpg",
    images: ["/images/women/perfume2.jpg"],
    tags: ["عطر", "نسائي", "مسكي", "جذاب"],
    description: "وصف عطر المساء",
    colors: ["بنفسجي", "أزرق"],
  },
  {
    id: 20,
    name: "بخاخ جسم بودري",
    brand: "Body Spray",
    category: "women",
    subCategory: "بخاخات نسائية",
    price: 251,
    old_price: 300,
    stock: 1,
    image: "/images/women/spray1.jpg",
    images: ["/images/women/spray1.jpg"],
    tags: ["عطر", "نسائي", "بخاخ", "بودري"],
    description: "وصف بخاخ جسم بودري",
    colors: ["رمادي", "أبيض"],
  },
  {
    id: 21,
    name: "بخاخ جسم فاكهي",
    brand: "Body Spray",
    category: "women",
    subCategory: "بخاخات نسائية",
    price: 280,
    old_price: 300,
    stock: 1,
    image: "/images/women/spray2.jpg",
    images: ["/images/women/spray2.jpg"],
    tags: ["عطر", "نسائي", "بخاخ", "فاكهي"],
    description: "وصف بخاخ جسم فاكهي",
    colors: ["أحمر", "رمادي"],
  },
  {
    id: 22,
    name: "محفظة حريمي جلدية",
    brand: "Leather Wallet",
    category: "women",
    subCategory: "محافظ نسائية",
    price: 200,
    old_price: 250,
    stock: 1,
    image: "/images/women/wallet1.jpg",
    images: ["/images/women/wallet1.jpg"],
    tags: ["محفظة", "نسائي", "جلد", "صغيرة"],
    description: "وصف محفظة حريمي جلدية",
    colors: ["بني", "وردي"],
  },
  {
    id: 23,
    name: "محفظة حريمي صغيرة",
    brand: "Fabric Wallet",
    category: "women",
    subCategory: "محافظ نسائية",
    price: 150,
    old_price: 200,
    stock: 1,
    image: "/images/women/wallet2.jpg",
    images: ["/images/women/wallet2.jpg"],
    tags: ["محفظة", "نسائي", "قماش", "عملية"],
    description: "وصف محفظة حريمي صغيرة",
    colors: ["بيج", "أسود"],
  },
  {
    id: 24,
    name: "نظارة شمسية كلاسيكية",
    brand: "Chanel",
    category: "women",
    subCategory: "نظارات شمسية نسائية",
    price: 500,
    old_price: 700,
    stock: 1,
    image: "/images/women/sunglasses1.jpg",
    images: ["/images/women/sunglasses1.jpg"],
    tags: ["نظارة", "نسائي", "شمسية", "كلاسيكية"],
    description: "وصف نظارة شمسية كلاسيكية",
    colors: ["أسود", "ذهبي"],
  },
  {
    id: 25,
    name: "نظارة شمسية حديثة",
    brand: "Gucci",
    category: "women",
    subCategory: "نظارات شمسية نسائية",
    price: 600,
    old_price: 800,
    stock: 1,
    image: "/images/women/sunglasses2.jpg",
    images: ["/images/women/sunglasses2.jpg"],
    tags: ["نظارة", "نسائي", "شمسية", "حديثة"],
    description: "وصف نظارة شمسية حديثة",
    colors: ["فضي", "أزرق"],
  },
  {
    id: 26,
    name: "اكسسوار ذهبي",
    brand: "Gold Accessories",
    category: "women",
    subCategory: "اكسسوارات نسائية",
    price: 100,
    old_price: 150,
    stock: 1,
    image: "/images/women/accessories1.jpg",
    images: ["/images/women/accessories1.jpg"],
    tags: ["اكسسوار", "نسائي", "ذهبي", "أنيق"],
    description: "وصف اكسسوار ذهبي",
    colors: ["ذهبي"],
  },
  {
    id: 27,
    name: "اكسسوار فضي",
    brand: "Silver Accessories",
    category: "women",
    subCategory: "اكسسوارات نسائية",
    price: 120,
    old_price: 180,
    stock: 1,
    image: "/images/women/accessories2.jpg",
    images: ["/images/women/accessories2.jpg"],
    tags: ["اكسسوار", "نسائي", "فضي", "بسيط"],
    description: "وصف اكسسوار فضي",
    colors: ["فضي"],
  },
  {
    id: 28,
    name: "ساعة اطفال جلد احمر",
    brand: "Kids Rolex",
    category: "kids",
    subCategory: "ساعات اطفال",
    price: 350,
    old_price: 450,
    stock: 1,
    image: "/images/kids/watch1.jpg",
    images: ["/images/kids/watch1.jpg"],
    tags: ["ساعة", "اطفال", "جلد", "ملونة"],
    description: "وصف ساعة اطفال جلد احمر",
    colors: ["أحمر", "أزرق"],
  },
  {
    id: 29,
    name: "ساعة رقمية",
    brand: "Digital Watch",
    category: "kids",
    subCategory: "ساعات اطفال",
    price: 380,
    old_price: 450,
    stock: 1,
    image: "/images/kids/watch2.jpg",
    images: ["/images/kids/watch2.jpg"],
    tags: ["ساعة", "اطفال", "رياضية", "رقمية"],
    description: "وصف ساعة رقمية",
    colors: ["أبيض", "أزرق"],
  },
  {
    id: 30,
    name: "ساعة اطفال كلاسيكية",
    brand: "Kids Rolex",
    category: "kids",
    subCategory: "ساعات اطفال",
    price: 340,
    old_price: 450,
    stock: 1,
    image: "/images/kids/watch3.jpg",
    images: ["/images/kids/watch3.jpg"],
    tags: ["ساعة", "اطفال", "جلد", "كلاسيكية"],
    description: "وصف ساعة اطفال كلاسيكية",
    colors: ["رمادي", "أسود"],
  },
  {
    id: 31,
    name: "ساعة اطفال معدن",
    brand: "Metal Watch",
    category: "kids",
    subCategory: "ساعات اطفال",
    price: 380,
    old_price: 450,
    stock: 1,
    image: "/images/kids/watch4.jpg",
    images: ["/images/kids/watch4.jpg"],
    tags: ["ساعة", "اطفال", "معدن", "بسيطة"],
    description: "وصف ساعة اطفال معدن",
    colors: ["أصفر", "وردي"],
  },
  {
    id: 32,
    name: "ساعة اطفال ملونة",
    brand: "Kids Rolex",
    category: "kids",
    subCategory: "ساعات اطفال",
    price: 350,
    old_price: 450,
    stock: 1,
    image: "/images/kids/watch1.jpg",
    images: ["/images/kids/watch1.jpg"],
    tags: ["ساعة", "اطفال", "جلد", "ملونة"],
    description: "وصف ساعة اطفال ملونة",
    colors: ["أحمر", "أزرق"],
  },
  {
    id: 33,
    name: "لعبة باز يطير",
    brand: "Toy Story",
    category: "kids",
    subCategory: "العاب اطفال",
    price: 275,
    old_price: 350,
    stock: 1,
    image: "/images/kids/toy1.jpg",
    images: ["/images/kids/toy1.jpg"],
    tags: ["لعبة", "اطفال", "شخصية", "مغامرة"],
    description: "وصف لعبة باز يطير",
    colors: ["أبيض", "أخضر"],
  },
  {
    id: 34,
    name: "لعبة وودي",
    brand: "Toy Story",
    category: "kids",
    subCategory: "العاب اطفال",
    price: 275,
    old_price: 350,
    stock: 1,
    image: "/images/kids/toy2.jpg",
    images: ["/images/kids/toy2.jpg"],
    tags: ["لعبة", "اطفال", "شخصية", "مغامرة"],
    description: "وصف لعبة وودي",
    colors: ["بني", "أصفر"],
  },
  {
    id: 35,
    name: "علبة مكياج",
    brand: "Makeup Sets",
    category: "kids",
    subCategory: "العاب اطفال",
    price: 165,
    old_price: 200,
    stock: 1,
    image: "/images/kids/toy3.jpg",
    images: ["/images/kids/toy3.jpg"],
    tags: ["لعبة", "بنات", "تجميل", "ملونة"],
    description: "وصف علبة مكياج",
    colors: ["وردي", "أحمر"],
  },
  {
    id: 36,
    name: "علبة خرز للبنات",
    brand: "Beads Sets",
    category: "kids",
    subCategory: "العاب اطفال",
    price: 90,
    old_price: 110,
    stock: 1,
    image: "/images/kids/toy4.jpg",
    images: ["/images/kids/toy4.jpg"],
    tags: ["لعبة", "بنات", "يدوية", "ملونة"],
    description: "وصف علبة خرز للبنات",
    colors: ["أزرق", "أحمر"],
  },
  {
    id: 37,
    name: "علبة خرز بسيطة",
    brand: "Beads Sets",
    category: "kids",
    subCategory: "العاب اطفال",
    price: 90,
    old_price: 110,
    stock: 1,
    image: "/images/kids/toy5.jpg",
    images: ["/images/kids/toy5.jpg"],
    tags: ["لعبة", "بنات", "يدوية", "بسيطة"],
    description: "وصف علبة خرز بسيطة",
    colors: ["أبيض", "وردي"],
  },
  {
    id: 38,
    name: "محفظة فرو ناعمة",
    brand: "Fur Wallets",
    category: "kids",
    subCategory: "محافظ فرو",
    price: 200,
    old_price: 250,
    stock: 1,
    image: "/images/kids/wallet1.jpg",
    images: ["/images/kids/wallet1.jpg"],
    tags: ["محفظة", "بنات", "فرو", "ناعمة"],
    description: "وصف محفظة فرو ناعمة",
    colors: ["بني", "أسود"],
  },
  {
    id: 39,
    name: "محفظة قماش صغيرة",
    brand: "Fabric Wallets",
    category: "kids",
    subCategory: "محافظ فرو",
    price: 150,
    old_price: 200,
    stock: 1,
    image: "/images/kids/wallet2.jpg",
    images: ["/images/kids/wallet2.jpg"],
    tags: ["محفظة", "بنات", "قماش", "صغيرة"],
    description: "وصف محفظة قماش صغيرة",
    colors: ["وردي", "بيج"],
  },
  {
    id: 2,
    name: "محفظة جلد طبيعية",
    brand: "Montblanc",
    category: "men",
    subCategory: "محافظ رجالية",
    price: 350,
    old_price: 450,
    stock: 15,
    new_arrival: true,
    rating: 4.7,
    image: "/images/men/wallet1.jpg",
    images: ["/images/men/wallet1.jpg", "/images/men/wallet1-1.jpg"],
    tags: ["محفظة", "رجالي", "جلد", "فاخرة"],
    description: "محفظة مصنوعة من الجلد الطبيعي، متينة وعصرية بلمسات فاخرة.",
    colors: ["بني", "أسود"],
  },

];

export const giftOptions: GiftOption[] = [
    {
      id: 101,
      name: "صندوق هدايا فاخر",
      category: "boxes",
      price: 150,
      stock: 5,
      image: "/images/box.png",
      tags: ["صندوق", "هدايا", "تغليف", "فاخر"]
    },
    {
      id: 102,
      name: "صندوق هدايا خشبي",
      category: "boxes",
      price: 120,
      stock: 3,
      image: "/images/box.png",
      tags: ["صندوق", "هدايا", "تغليف", "خشبي"]
    },
     {
       id: 103,
        name: "تغليف هدايا ذهبي",
       category: "packets",
      price: 50,
        stock: 10,
        image: "/images/packet.png",
        tags: ["تغليف", "هدايا", "ورق", "ذهبي"]
     },
      {
         id: 104,
          name: "تغليف هدايا ملون",
         category: "packets",
       price: 60,
         stock: 8,
         image: "/images/packet.png",
          tags: ["تغليف", "هدايا", "ورق", "ملون"]
      },
       {
         id: 105,
          name: "علبة شوكولاتة فاخرة",
        category: "chocolates",
          price: 200,
          stock: 10,
          image: "/images/chocolates.png",
          tags: ["شوكولاتة"]
       },
       {
         id: 1017,
          name: "علبة شوكولاتة فاخرة",
        category: "chocolates",
          price: 200,
          stock: 10,
          image: "/images/chocolates.png",
          tags: ["شوكولاتة"]
       },
       {
          id: 106,
           name: "شوكلاته مشكله ",
         category: "chocolates",
         price: 180,
         stock: 7,
         image: "/images/chocolates.png",
         tags: ["شوكولاتة", "حلويات", "مشكلة", "هدية"]
       },
       {
         id: 107,
         name: "شيبسي دوريتوس",
         category: "candies",
         price: 20,
         stock: 15,
         image: "/images/chips.png",
         tags: ["شيبسي", "مقرمشات", "وجبات_خفيفة", "مالحة"]
       },
        {
           id: 108,
           name: "شيبسي حار",
          category: "candies",
          price: 25,
          stock: 12,
          image: "/images/chips.png",
          tags: ["شيبسي", "مقرمشات", "وجبات_خفيفة", "حارة"]
        },
        {
          id: 109,
            name: "حلوى مصاص",
           category: "candies",
           price: 15,
           stock: 20,
           image: "/images/candy.png",
           tags: ["حلوى", "مصاص", "حلويات", "ملونة"]
         },
        {
           id: 110,
            name: "حلوى جيلي",
            category: "candies",
          price: 18,
          stock: 18,
          image: "/images/candy.png",
          tags: ["حلوى", "جيلي", "حلويات", "متنوعة"]
        },
         {
           id: 111,
            name: "بالونات ملونة",
            category: "decoration",
            price: 30,
            stock: 10,
            image: "/images/decoration.png",
            tags: ["بالونات", "زينة", "حفلات", "ملونة"]
         },
         {
           id: 112,
            name: "شريط زينة",
           category: "decoration",
           price: 20,
           stock: 25,
           image: "/images/decoration.png",
           tags: ["شريط", "زينة", "حفلات", "بسيط"]
         }
];